# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_name=Genesis Framework
mod_id=genesisframework
mod_version=1.1.2
mod_authors=uhmbyee / Mariany Pinkston
mod_description=A framework for creating custom age progression systems.
mod_page_url=https://www.curseforge.com/minecraft/mc-mods/genesis-framework
mod_git_url=https://github.com/marianyp/genesis-framework
mod_license=MPL-2.0

maven_group=dev.mariany.genesisframework
archives_base_name=genesisframework

# Dependencies
fabric_api_version=0.155.2+26.2
rei_version=26.2.820
jei_version=30.16.0.124
